sonar.projectKey=vanshita-lilbigthings_cicd-setup
sonar.organization=vanshita-lilbigthings
sonar.projectName=cicd-setup
sonar.projectVersion=1.0

# Source files
sonar.sources=src
sonar.tests=tests

# Coverage report path
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclude files
sonar.exclusions=node_modules/**,coverage/**